---
title: "Modified Interaction Plots for GSS Data"
author: "Todd E Bodner, PhD & Joel S Steele, PhD"
date: "December 20, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(comment='')
```

```{r}
# Things needed for Tumbleplots.
# 1) Set up the moderation regression for the outcome.
# 2) Set up the regression for the target and moderator variable
# 3) Get the mean and sd for the moderator.
# 4) Get the mean and sd for the target predictor.
# 5) Compute 1 sd above and 1 sd below mean for moderator.
# 6) Plot tumble.
# 7) Plot scatter with jitter. 
# 8) Store the outcome, target, and moderator.
# 9) Store the dataframe used for the models.

library(foreign)
data <- read.spss("gssspssreduced.sav", to.data.frame=TRUE)

tumble_set = function(dat, outcome, target, moderator) {
  #=================#
  # Regression Models
  #=================#
  # full interaction model
  formula_intrxn = as.formula(paste(outcome,'~',target,"*",moderator))
  intrxn_model = lm(formula_intrxn,data=dat)

  # model between predictors
  formula_inputs = as.formula(paste(target,'~',moderator))
  inputs_model = lm(formula_inputs,data=dat)

  #=================#
  # descriptives
  #=================#
  # descriptives for predictor inputs
  target_desc = c('mean'=mean(dat[,target]),
                  'sd'=sd(dat[,target]))
  moderator_desc = c('mean'=mean(dat[,moderator]),
                     'sd'=sd(dat[,moderator]))
  
  # +/- 1 SD values for moderator
  lowmod <- moderator_desc['mean']-moderator_desc['sd']
  highmod <- moderator_desc['mean']+moderator_desc['sd']

  # prediction based on the model
  # target mean, low and high moderator
  moderator_prediction_data = data.frame(c(lowmod,highmod))
  names(moderator_prediction_data) = names(coef(inputs_model))[-1]
  moderator_predicted_targets = predict(
    inputs_model, moderator_prediction_data)

  target_residual = summary(inputs_model)$sigma

  adjusted_predicted_targets = c(
    rep(moderator_predicted_targets,each=2) 
    + rep(c(-1,1)*target_residual,times=2)
    )
  names(adjusted_predicted_targets)=c("ltlm","htlm","lthm","hthm")

  # construct the prediction data data.frame
  prediction_data = data.frame(
    adjusted_predicted_targets,
    c(lowmod,lowmod,highmod,highmod),
    c(adjusted_predicted_targets * c(lowmod,lowmod,highmod,highmod))
    )
  names(prediction_data) = names(coef(intrxn_model))[-1]
  # add some factor labels
  prediction_data = cbind(prediction_data, 
                          'target'=rep(c('low','high'),times=2), 
                          'moderator'=rep(c('low','high'),each=2))
  
  tumble_predictions = predict(intrxn_model, prediction_data)
  # update our data.frame
  prediction_data$tumble_values = tumble_predictions
  
  return(
    list('interaction_model'=intrxn_model,
         'input_model'=inputs_model,
         'tumble_data'=prediction_data,
         
         'target'=target,
         'moderator'=moderator,
         'outcome'=outcome,
         'target_desc'=target_desc,
         'moderator_desc'=moderator_desc,
         'highmod'=highmod,
         'lowmod'=lowmod)
  
  )
}

GSS_tumble = tumble_set(data, 'prestg80','educ','maeduc')

tumble_plot=function(tumble_dat, axis_labels=c('x','y'),legend_title=NA){

  target = tumble_dat$target
  plot_data = tumble_dat$tumble_data
  
  plot(NA, 
       xlim=range(plot_data[,target]), 
       ylim=range(plot_data[,"tumble_values"]), 
       ann=FALSE)
  plot_formula = as.formula(paste("tumble_values","~",target))

  lines(plot_formula, 
        data=plot_data[plot_data$moderator=='high',],
        type='o')
  lines(plot_formula, 
        data=plot_data[plot_data$moderator!='high',],
        type='o', lty='dashed')
  
  mtext(axis_labels[1], side=1, line=2.5, cex=1)
  mtext(axis_labels[2], side=2, line=2.5, cex=1)
  
  if(!is.na(legend_title)){
    legend_text=c(
      paste(round(tumble_dat$highmod,3),'(1 SD Above Mean)'),
      paste(round(tumble_dat$lowmod,3),'(1 SD Below Mean)')
    )
    legend("topleft",legend_text,cex=.8,
           lty=c("solid","dashed"), 
           title=legend_title, 
           bty='n',inset=.01)
  }  
}

tumble_plot(GSS_tumble,
            axis_labels=c("Respondent's Years of Education",
                          "Predicted Occupational Prestige"), 
            legend_title = "Mother's Years of Education")

#Step 6
#Abstracted out code.
plot(NA, xlim=range(build_dat$tarpred), ylim=range(build_dat$newdatout), ann=FALSE)
with(build_dat[build_dat$moderator=='high',], lines(newdatout ~ tarpred, type='o'))
with(build_dat[build_dat$moderator!='high',], lines(newdatout ~ tarpred, type='o', lty='dashed'))
mtext("Respondent's Years of Education", side=1, line=2.5, cex=1)
mtext("Predicted Occupational Prestige", side=2, line=2.5, cex=1)
legend("topleft",c("14.2 Years (1 SD Above Mean)","7.3 Years (1 SD Below Mean)"),cex=.8, 
  lty=c("solid","dashed"), title="Mother's Years of Education", bty='n',inset=.01)


# plot(NA, xlim=range(build_dat$tarpred), ylim=range(build_dat$newdatout), ann=FALSE)
# with(build_dat[build_dat$moderator=='high',], lines(newdatout ~ tarpred, type='o'))
# with(build_dat[build_dat$moderator!='high',], lines(newdatout ~ tarpred, type='o', lty='dashed'))
# mtext("Respondent's Years of Education", side=1, line=2.5, cex=1)
# mtext("Predicted Occupational Prestige", side=2, line=2.5, cex=1)
# legend("topleft",c("14.2 Years (1 SD Above Mean)","7.3 Years (1 SD Below Mean)"),cex=.8, 
#   lty=c("solid","dashed"), title="Mother's Years of Education", bty='n',inset=.01)

```
   
   
## Standard interaction Graph

Need to update this to match the format from above.

```{r}
mtar <- mean(tarpred)
sdtar <- sqrt(var(tarpred))
htar <- mtar + sdtar
ltar <- mtar - sdtar
shhhr <- predhr$coeff[1,1] + predhr$coeff[2,1]*htar + 
   predhr$coeff[3,1]*highmod + predhr$coeff[4,1]*htar*highmod
shlhr <- predhr$coeff[1,1] + predhr$coeff[2,1]*htar + 
   predhr$coeff[3,1]*lowmod + predhr$coeff[4,1]*htar*lowmod
slhhr <- predhr$coeff[1,1] + predhr$coeff[2,1]*ltar + 
   predhr$coeff[3,1]*highmod + predhr$coeff[4,1]*ltar*highmod
sllhr <- predhr$coeff[1,1] + predhr$coeff[2,1]*ltar + 
   predhr$coeff[3,1]*lowmod + predhr$coeff[4,1]*ltar*lowmod
sprep <- t(matrix(c(htar,shhhr,htar,shlhr,ltar,slhhr,ltar,sllhr),2,4))

plot(sprep[,1],sprep[,2],ann=FALSE, ylim=c(20,60),xlim=c(5,20))
segments(htar,shhhr,ltar,slhhr,lty="dashed")
segments(htar,shlhr,ltar,sllhr)
mtext("Respondent's Years of Education", side=1, line=2.5, cex=1)
mtext("Predicted Occupational Prestige", side=2, line=2.5, cex=1)
legend(6,55,c("14.2 Years (1 SD Above Mean)","7.3 Years (1 SD Below Mean)"),cex=.8, 
  lty=c("solid","dashed"), title="Mother's Years of Education")
```

### Both together
Also need to code up a way to use layout and display them both.

```{r}
#pdf("gssinteract.pdf", width = 8, height = 10 )
# op=par(mfrow=c(2,1))
# plot(sprep[,1],sprep[,2],ann=FALSE, ylim=c(30,60),xlim=c(8,18),pch=21)
# segments(htar,shhhr,ltar,slhhr)
# segments(htar,shlhr,ltar,sllhr,lty="dashed")
# mtext("Years of Education", side=1, line=2.5, cex=1)
# mtext("Predicted Occupational Prestige", side=2, line=2.5, cex=1)
# legend(7.7,60,c("14.2 Years (1 SD Above Mean)","7.3 Years (1 SD Below Mean)"),cex=.8, 
#   lty=c("solid","dashed"), title="Mother's Years of Education")
# plot(prep[,1],prep[,2],ann=FALSE, ylim=c(30,60),xlim=c(8,18),pch=24)
# segments(hthm,hhhr,lthm,lhhr)
# segments(htlm,hlhr,ltlm,llhr,lty="dashed")
# mtext("Years of Education", side=1, line=2.5, cex=1)
# mtext("Predicted Occupational Prestige", side=2, line=2.5, cex=1)
# legend(7.7,60,c("14.2 Years (1 SD Above Mean)","7.3 Years (1 SD Below Mean)"),cex=.8, 
#   lty=c("solid","dashed"), title="Mother's Years of Education")
# par(op)

# Bivariate Distribution of Target and Moderator

#pdf("gssbivariate.pdf", width = 8, height = 10)
plot(jitter(educ, factor=.4),jitter(maeduc,factor=.8),ann=FALSE,pch=20,cex=.6, col='grey60')
mtext("Years of Education", side=1, line=2.5, cex=1)
mtext("Mother's Years of Education", side=2, line=2.5, cex=1)
abline(v = ltar, lty="dashed")
abline(v = htar)
abline(h = lowmod, lty="dashed")
abline(h = highmod)
legend(0,20,c("1 SD Below Mean","1 SD Above Mean"),cex=.8, lty=c("dashed","solid"), title="Reference Lines")
points(hthm,highmod,pch=17)
points(htlm,lowmod,pch=17)
points(lthm,highmod,pch=17)
points(ltlm,lowmod,pch=17)
points(htar,highmod,pch=19)
points(htar,lowmod,pch=19)
points(ltar,highmod,pch=19)
points(ltar,lowmod,pch=19)
# points(hthm,highmod,pch=24)
# points(htlm,lowmod,pch=24)
# points(lthm,highmod,pch=24)
# points(ltlm,lowmod,pch=24)
# points(htar,highmod,pch=21)
# points(htar,lowmod,pch=21)
# points(ltar,highmod,pch=21)
# points(ltar,lowmod,pch=21)

#pdf("gssbivariate.pdf", width = 8, height = 10)
# plot(jitter(educ, factor=.4),jitter(maeduc,factor=.4),ann=FALSE,pch=20)
# mtext("Years of Education", side=1, line=2.5, cex=1)
# mtext("Mother's Years of Education", side=2, line=2.5, cex=1)
# abline(v = ltar, lty="dashed")
# abline(v = htar)
# abline(h = lowmod, lty="dashed")
# abline(h = highmod)
# legend(0,20,c("1 SD Below Mean","1 SD Above Mean"),cex=.8, lty=c("dashed","solid"), title="Reference Lines")
# points(hthm,highmod,pch=24)
# points(htlm,lowmod,pch=24)
# points(lthm,highmod,pch=24)
# points(ltlm,lowmod,pch=24)
# points(htar,highmod,pch=21)
# points(htar,lowmod,pch=21)
# points(ltar,highmod,pch=21)
# points(ltar,lowmod,pch=21)

```


